name: Node CI

# Push tests pushes; PR tests merges
on: [push, pull_request]

jobs:

  # Test the build
  build:
    # Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    # Go
    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Set up Deno
      uses: denolib/setup-deno@master

    - name: Versions
      run: deno --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test
